server:
  port: 8088
spring:
  datasource:
    # url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
        # cluster-name: HZ
        # ephemeral: false # 是否是临时实例
        # namespace: 72fc3636-df4b-4437-ac25-4fb443c429d0
#  cloud:
#    nacos:
#      server-addr: nacos:8848 # nacos服务地址
#      discovery:
#        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
#        ephemeral: false # 是否是临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    serviceUrl:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#    instance:
#      preferIpAddress: true
userservice:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
#feign:
#  httpclient:
#    enabled: true # 支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数