server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://124.71.152.110:3306/cloud_hotel?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 124.71.152.110
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo